name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Build
        run: |
          npm install
          npx ng build --configuration production --base-href /
          cp dist/sloptri-portfolio/browser/index.html dist/sloptri-portfolio/browser/404.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/sloptri-portfolio/browser
          branch: master
