name: Build and Deploy
on:
  push:
    branches:
      - gh-pages
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Build
        run: |
          npm install
          npx ng build --configuration production --base-href /

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/sloptri.github.io/browser
          branch: gh-pages
